---
name: "JavScraper"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0-pre"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.JavScraper.dll"
changelog: >
  changelog
