name: '🔀 PR Rebase Command'

on:
  repository_dispatch:
    types:
      - rebase-command

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-rebase.yaml@master
    with:
      rebase-head: ${{ github.event.client_payload.pull_request.head.label }}
      repository-full-name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
